# -*- coding: utf-8 -*-
# @Time : 2024/9/25 16:29
# @Author : Shao0000
# @Email : Shao0000@aliyun.com
# @File : cn_en_map.py
# @Project : JDSZ

cn_en_map = {
    "jd1_1_01_jdsz": {
        "访客数": ("UV", "value"),
        "浏览量": ("PV", "value"),
        "人均浏览量": ("AvgDepth", "value"),
        "平均停留时长": ("AvgStayTime", "value"),
        "跳失率": ("SkipOut", "value"),
        "下单转化率": ("ToOrderRate", "value"),
        "成交转化率": ("ToOrdRate", "value"),
        "下单成交转化率": ("DealToOrderRate", "value"),
        "下单客户数": ("OrderCustNum", "value"),
        "下单单量": ("OrderNum", "value"),
        "下单金额": ("OrderAmt", "value"),
        "下单商品件数": ("OrderProNum", "value"),
        "成交客户数": ("OrdCustNum", "value"),
        "成交单量": ("OrdNum", "value"),
        "成交金额": ("OrdAmt", "value"),
        "成交商品件数": ("OrdProNum", "value"),
        "件单价": ("UnitPriceAvg", "value"),
        "客单价": ("CustPriceAvg", "value"),
        "取消及售后退款金额": ("CancelOrdAmt", "value"),
        "取消及售后退款件数": ("CancelSaleQty", "value"),
        "取消及售后退款单量": ("CancelOrdQty", "value"),
    },
    "jd1_1_09_jdsz": {
        "行业类目": ("SecondName", "ThirdName"),
        "上架商品数（SPU）": "ShelvesNumSPU",
        "上架商品数（SKU）": "ShelvesNumSKU",
        "访客数": "UV",
        "浏览量": "PV",
        "加购商品件数": "AddBuyGoodsNum",
        "成交客户数": "DealCustNum",
        "成交金额": "OrdAmt",
        "成交转化率": "DealCustRate",
    },
    "jd1_1_07_jdsz": {
        "退货量": ("NumTH", "value"),
        "换货量": ("NumChange", "value"),
        "返修量": ("NumFix", "value"),
        "退款金额": ("AmtTH", "value"),
        "退货率": ("THRate", "value"),
        "400连接率": ("ConnectRatio", "value"),
        "订单48H揽件率": ("CollectRatio", "value"),
        "售后服务时长": ("Duration", "value"),
        "交易纠纷率": ("OrdDisRatio", "value"),
    },
    "jd1_1_02_jdsz": {
        "访客数": "goodsVisitorNum",
        "浏览量": "goodsBrowseNum",
        "商品关注数": "goodsConcernNum",
        "加购商品件数": "addBuyGoodsPieceNum",
        "加购人数": "addBuyCustNum",
        "成交客户数": "ordCustNum",
        "成交单量": "ordNum",
        "成交商品件数": "ordGoodsPieceNum",
        "成交金额": "ordAmt",
        "成交转化率": "goodsConverRate",
        "UV价值": "uvValue",
        "最近上架时间": "shelvesDate",
        "商品ID": "spuId",
        "是否为商品": "$hasChildren",
        "详情页跳出率": "ProSkipOut",
        "曝光量": "ExposureNum",
        "点击次数": "ClickNum",
        "点击率": "ClickRate",
        "系统预测未来7天销量": "ForecastSalesNum",
        "下单客户数": "OrderCustNum",
        "下单商品件数": "OrderGoodsPieceNum",
        "下单金额": "OrderAmt",
        "下单成交转化率": "DealToOrderRate",
        "下单转化率": "ToOrderRate",
        "PV现货率": "PvRate",
        "客单价": "CustPriceAvg",
        "件单价": "UnitPriceAvg",
        "商品名称": "proName",
    },
    "jd1_1_06_jdsz": {
        "访客数": "goodsVisitorNum",
        "浏览量": "goodsBrowseNum",
        "商品关注数": "goodsConcernNum",
        "加购商品件数": "addBuyGoodsPieceNum",
        "加购人数": "addBuyCustNum",
        "成交客户数": "ordCustNum",
        "成交单量": "ordNum",
        "成交商品件数": "ordGoodsPieceNum",
        "成交金额": "ordAmt",
        "成交转化率": "goodsConverRate",  # noqa
        "UV价值": "uvValue",
        "最近上架时间": "shelvesDate",
        "skuID": "spuId",
        "是否为商品": "$hasChildren",
        "详情页跳出率": "ProSkipOut",
        "曝光量": "ExposureNum",
        "点击次数": "ClickNum",
        "点击率": "ClickRate",
        "系统预测未来7天销量": "ForecastSalesNum",
        "下单客户数": "OrderCustNum",
        "下单商品件数": "OrderGoodsPieceNum",
        "下单金额": "OrderAmt",
        "下单成交转化率": "DealToOrderRate",
        "下单转化率": "ToOrderRate",
        "PV现货率": "PvRate",
        "客单价": "CustPriceAvg",
        "件单价": "UnitPriceAvg",
        "商品名称": "proName",
    },
    "jd1_1_04_jdsz": {
        "有效粉丝总数": ("FansMember", "VCustNum", "value"),
        "有效新增粉丝数": ("FansMember", "VNewCustNum", "value"),
        "有效净增粉丝数": ("FansMember", "VNetCustNum", "value"),
        "粉丝进店访客数": ("FansVisit", "ShopUV", "value"),
        "粉丝进店浏览量": ("FansVisit", "ShopPV", "value"),
        "商详流量粉丝占比": ("FansVisit", "DetPVRate", "value"),
        "店铺流量粉丝占比": ("FansVisit", "ShopPVRate", "value"),
        "粉丝成交客户数": ("FansDeal", "OrdCustNum", "value"),
        "粉丝成交单量": ("FansDeal", "OrdNum", "value"),
        "粉丝成交金额": ("FansDeal", "OrdAmt", "value"),
        "粉丝成交客单价": ("FansDeal", "CustPriceAvg", "value"),
        "粉丝成交转化率": ("FansDeal", "ToOrdRate", "value"),
        "粉丝30天复购率": ("FansDeal", "The30RepBuyRate", "value"),
        "粉丝90天复购率": ("FansDeal", "The90RepBuyRate", "value"),
    },
    "jd1_1_05_jdsz": {
        "有效会员总数": "jdr_sch_user_authentication_member_shop_cnt_shopversion_brandmem@date_end&brandmem_card",
        "有效净增会员数": "jdr_sch_user_authentication_member_shop_cnt_shopversion_brandmem_increase@brandmem_card",
        "有效新增会员数": "jdr_sch_user_open_member_shop_cnt_shopversion_brandmem@brandmem_card",
        "有效解绑会员数": "jdr_sch_user_invalid_member_shop_cnt_shopversion_brandmem@brandmem_card",
        "会员进店访客数": "jdr_sch_mkt_brow_shop_cnt_shopversion_brandmem_sz@brandmem_card&browse_brand",
        "会员进店浏览量": "jdr_sch_mkt_brow_shop_qtty_shopversion_brandmem_sz@brandmem_card&browse_brand",
        "商品会员浏览量": "jdr_sch_mkt_brow_sku_qtty_shopversion_brandmem_sz@brandmem_card&browse_brand",
        "商品会员关注数": "jdr_sch_user_follow_sku_sku_qtty_shopversion_brandmem@brandmem_card&follow_brand",
        "加购会员数": "jdr_sch_mkt_brow_shop_cnt_shopversion_brandmem_sz@brandmem_card&add_cart",
        "会员成交客户数": "jdr_sch_mkt_deal_ord_ord_cnt_shopversion_brandmem_sz@brandmem_card",
        "会员成交单量": "jdr_sch_mkt_deal_ord_ord_dis_qtty_shopversion_brandmem_sz@brandmem_card",
        "会员成交金额": "jdr_sch_mkt_deal_ord_ord_amt_shopversion_brandmem_sz@brandmem_card",
        "会员成交客单价": [
            "jdr_sch_mkt_deal_ord_ord_amt_shopversion_brandmem_sz@brandmem_card",
            "/",
            "jdr_sch_mkt_deal_ord_ord_cnt_shopversion_brandmem_sz@brandmem_card",
        ],
        "会员成交转化率": [
            "jdr_sch_mkt_deal_ord_ord_cnt_shopversion_brandmem_sz@brandmem_card",
            "/",
            "jdr_sch_mkt_brow_shop_cnt_shopversion_brandmem_sz@brandmem_card&browse_brand",
        ],
        "会员30天复购率": [
            "jdr_sch_mkt_deal_ord_ord_cnt_shopversion_brandmem_sz_ld30_rebuy_brandmem_card",
            "/",
            "jdr_sch_mkt_deal_ord_ord_cnt_shopversion_brandmem_sz_brandmem_card_ld30",
        ],
        "会员90天复购率": [
            "jdr_sch_mkt_deal_ord_ord_cnt_shopversion_brandmem_sz_rebuy_90d_brandmem_card",
            "/",
            "jdr_sch_mkt_deal_ord_ord_cnt_shopversion_brandmem_sz_brandmem_card_90d",
        ],
        "30天复购会员数": "jdr_sch_mkt_deal_ord_ord_cnt_shopversion_brandmem_sz_ld30_rebuy_brandmem_card",
        "30天成交客户": "jdr_sch_mkt_deal_ord_ord_cnt_shopversion_brandmem_sz_brandmem_card_ld30",
        "90天复购会员数": "jdr_sch_mkt_deal_ord_ord_cnt_shopversion_brandmem_sz_rebuy_90d_brandmem_card",
        "90天成交客户数": "jdr_sch_mkt_deal_ord_ord_cnt_shopversion_brandmem_sz_brandmem_card_90d",
        "沉寂会员数": "jdr_sch_user_authentication_member_shop_cnt_shopversion_brandmem_client@brandmem_card",
    },
}
